defaults: &defaults
  title: "btcall"
  description: "bitcoin"
  site_name: "btcall"
  spider_interval: 5 * 60
  spider_usd_rmb_interval: 5 * 60
  default_email_sender: "admin@btcall.com"
  host: "121.40.129.130"
  max_allowed_value: 1
  send_email_enabled: false

development:
  <<: *defaults
  spider_interval: 10
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  host: "btcall"
