defaults: &defaults
  title: "900bit.com"
  description: "bitcoin"
  site_name: "900bit"
  cn_site_name: "900bit"
  spider_interval: 5 * 60
  spider_usd_rmb_interval: 5 * 60
  default_email_sender: "noreply@900bit.com"
  host: "121.40.129.130"
  max_allowed_value: 1
  send_email_enabled: true
  odds: 1.9
  listtransactions_count: 50
  blacklists: ["14.17.34.191"]
  platform_interest: 0.01
  bitcoind:
    host: 'localhost'
    user: 'bitcoinrpc'
    password: 'a98bb3ac968ec4d48f578b12baa9bd86'
    port: '8332'

development:
  <<: *defaults
  spider_interval: 10
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  host: "www.900bit.com"
  bitcoind:
    host: '207.226.141.226'
    user: 'bitcoinrpc'
    password: 'E5gXa2k3er4vcifUutKGxSWVF3qVuozAfGt229DWJ5fe'
    port: '8332'
