defaults: &defaults
  title: "btcall"
  description: "bitcoin"
  site_name: "btcall"
  spider_interval: 5 * 60
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  spider_interval: 10
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
